In [ ]:
9a=10 #printing variable
print("I am ",10,"years old")


I am  10 years old


In [ ]:
l=list(map(int,input("enter data:").split()))
print("addition is ",sum(l))

enter data:1234567 23456789 3456789 23456789 3456789 3456789 32456789 345678 345678 345678 
addition is  92012335


In [ ]:
a,b=map(int, input("enter a and b values :").split())#arithematic of numbers
print("addition is",a+b)
print("difference is ",a-b)
print("multiplication is ",a*b)
print("remainder is ",a%b)
print("division is ",round(a/b,2))
print("Exp is ",a**b)

enter a and b values :9 3
addition is 12
difference is  6
multiplication is  27
remainder is  0
division is  3.0
Exp is  729


In [ ]:
''' take a number from the user which is a salary if the salary is more than equal to 50,000 there is a 10 % tax print his final salary'''
user=int(input("Enter your salary"));
if(user >=50000):
  print("your salary including taxes is ",(user-((10*user)/100)))
else:
  print("your salary including taxes is ",user)


Enter your salary100000
your salary including taxes is  90000.0


In [ ]:
#relational operator and conditional operator
'''get the salary from the user if the salary is more than or equal to 50,000 apply 10 % tax deduction if the salary is < than 50,000 apply 5% tax
if the slalary is more than 70,000 apply 12 % tax if the salary exit 1,00,000 print your are promoted to next level'''
user=int(input("Enter your salary"));
if(user <50000):
  print("your salary including taxes is ",(user-((5*user)/100)))
elif (user < 70000):
   print("your salary including taxes is ",(user-((10*user)/100)))
elif(user <100000):
   print("your salary including taxes is ",(user-((12*user)/100)))
else:
  print("your are promoted to next level")

Enter your salary59809
your salary including taxes is  53828.1


In [ ]:
#creating tables using for loop
n=int(input("enter n value"))
l=list(i for i in range(1,n+2))
for i in range(0,10):
  print((n) ,'*',(l[i]),"=",((n)*l[i]))


enter n value21
21 * 1 = 21
21 * 2 = 42
21 * 3 = 63
21 * 4 = 84
21 * 5 = 105
21 * 6 = 126
21 * 7 = 147
21 * 8 = 168
21 * 9 = 189
21 * 10 = 210


In [ ]:
#creating tables using while loop
n=int(input("enter n value"))
i=1
while(i!=11):
  print(n,"*",i,"=",n*i)
  i=i+1


enter n value99
99 * 1 = 99
99 * 2 = 198
99 * 3 = 297
99 * 4 = 396
99 * 5 = 495
99 * 6 = 594
99 * 7 = 693
99 * 8 = 792
99 * 9 = 891
99 * 10 = 990


In [ ]:
#heterogeneous
l=[1,"hii",'a',23.42,True]
for i in l:
  print(i)

1
hii
a
23.42
True


In [ ]:
# append and extend and insert
l1=[]
l1.append("hii") #listName.append(element)
l1.append(1)
l1.append("how are you")
l1.append(9)
l1.insert(3,"you are here")#listName.insert(index,element)
l2=[1,2,3,9]
l1.extend(l2)#list1.extend(list2)
print(l1)

['hii', 1, 'how are you', 9]


In [ ]:
# pop and remove

l1.pop(3)#listName.pop(index)
l1.remove(1)#listName.remove(element)
print(l1)

['hii', 'how are you', 'you are here', 2, 3, 9]


In [ ]:
#list is clear list name is exist but elements delete
l1.clear()
print(l1)


[]


In [ ]:
'''create a list of integers (10 ) print their squares save this list in new list'''
l3=[i*i for i in range(1,50) if(i%2==0) ]#using list comprehension
print(l3)                                #l=[item for item in range(n) condition]

[4, 16, 36, 64, 100, 144, 196, 256, 324, 400, 484, 576, 676, 784, 900, 1024, 1156, 1296, 1444, 1600, 1764, 1936, 2116, 2304]


In [ ]:
l4=[22,66,12,36,69]
res=[i*i if(i>50) else 'x' for i in l4 ]#l=[statement ifcondition else else statement for i in list ]
print(res)

['x', 4356, 'x', 'x', 4761]


In [ ]:
'''take the salary from the user if the salary is less than 50,000 10 % tax other wise 15 % tax'''
n=[200,242432,4242,13242]
l=[(salary-salary*(0.1)) if(salary < 50000) else (salary-salary*(15/100)) for salary in n]
print(l)

[180.0, 206067.2, 3817.8, 11917.8]


In [ ]:
'''Dictionary
dict_1={key1:values,key2:values,....}'''
dict_1={1:"mon",2:"tues",3:"wed",4:"thurs",5:"friday",6:"satur",7:"sun"}
print(dict_1)
dict_1={1:"mon",2:"tues",3:"wed",4:"thurs",5:"friday",6:"satur",7:"sun",1:"monday"}#unique key is used if we rewrite the key the old key get delete
print(dict_1)
print(dict_1.keys())#to display only keys
print(dict_1.values())#to display only values
''' to access any value'''
print(dict_1[4])#to display only 4 key value


{1: 'mon', 2: 'tues', 3: 'wed', 4: 'thurs', 5: 'friday', 6: 'satur', 7: 'sun'}
{1: 'monday', 2: 'tues', 3: 'wed', 4: 'thurs', 5: 'friday', 6: 'satur', 7: 'sun'}
dict_keys([1, 2, 3, 4, 5, 6, 7])
dict_values(['monday', 'tues', 'wed', 'thurs', 'friday', 'satur', 'sun'])
thurs


In [ ]:
dict_2={"Dept":"CSE","details":{"year":2,"section":'D',"count":72}}
print(dict_2["details"]["section"])
print(dict_2["details"].values())
print(dict_2["details"].keys(), "is",dict_2["details"].values())
print("year  is ",dict_2["details"]["year"])
print("section is",dict_2["details"]["section"])
print("count is",dict_2["details"]["count"])

D
dict_values([2, 'D', 72])
dict_keys(['year', 'section', 'count']) is dict_values([2, 'D', 72])
year  is  2
section is D
count is 72


In [ ]:
l=[1,2,3,9]
l2=["hii","how","are","you"]

dict_3=dict((zip(l,l2)))
print(dict_3)


{1: 'hii', 2: 'how', 3: 'are', 9: 'you'}


In [ ]:
import numpy as np
a=np.array([1,2,3,4])#1D array
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
print(a.ndim)
print(a.shape)

1
(4,)


In [ ]:
a2=np.array([[1,2,3,4],[2,4,6,9],[5,6,7,9]]) #2D array
print(a2)
print(type(a2))
print(a2.ndim)#2 because it is 2D
print(a2.shape)#(rows,columns)=(3,4)


[[1 2 3 4]
 [2 4 6 9]
 [5 6 7 9]]
<class 'numpy.ndarray'>
2
(3, 4)


In [ ]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[9,8,7],[6,5,4],[3,2,1]]])# [parents[groups[rows],[rows]],[groups[rows],[rows]]]
print(a3)
print(type(a3))
print(a3.ndim)
print(a3.shape)#(groups,rows,columns)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 7]
  [6 5 4]
  [3 2 1]]]
<class 'numpy.ndarray'>
3
(2, 3, 3)


In [ ]:
a1=np.ones((2,3))#(rows,columns) all ones will print
print(a1)
a4=np.ones((2,3,4))#(groups,rows,columns)
print(a4)

[[1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
a0=np.zeros((2,2,4))#prints zeroes
print(a0)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
ad=np.eye(4)#np.eye(rows) diagonal values
print(ad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
ar=np.arange(1,10,2) #(start,stop,step)
print(ar)
print(type(ar))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
'''print all the numbers that are divisible by 8 using a range function between 1 and 1000'''
ar1=np.arange(8,1001,8)
print(ar1)

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [ ]:
al=np.linspace(2,4,10)#(lowerbound,upperbound,number of halfs)
print(al)#linspaces=spliting a range into n numbers with common differences

[2.         2.22222222 2.44444444 2.66666667 2.88888889 3.11111111
 3.33333333 3.55555556 3.77777778 4.        ]


In [ ]:
'''typles and sets and documentation'''

In [ ]:
l=[1,2,3,4] #conversion from list to tuple
t=tuple(l)
print(t)
#indexing
print(t[3])
a=1,
print(type(a))#comma represents it is a tuple
print(len(t))#length of tuple
print(t[:2])#tuple slicing
a,b,c=(1,2,3)#allocating values
print(a)
print(b)
print(c)
print(3 in t) #membership operator in tuple
t=list(t)
t.append(9)
t=tuple(t)
print(t)

(1, 2, 3, 4)
4
<class 'tuple'>
4
(1, 2)
1
2
3
True
(1, 2, 3, 4, 9)


In [ ]:
t=list(t)
t.remove(1)
t=tuple(t)
print(t)


(3, 4, 9)


In [ ]:
#sets
s={1,2,3,4}
print(type(s))#it is a type of set
print(s)#indexes are always changes
s1={1,2,36,36,91}#no duplicate values
print(s1)
l=["hii","here"]
s2=set(l)#type conversion
print(s2)
#add values
s3={1,2,3}
s3.add(4)
print(s3)
#for inserting multiple data
s4={3,6,9}
s4.update([1,2,3])
print(s4)
#removing an element
s4.discard(2)
print(s4)
a={1,2,3,4,6}
b={1,2,6,9}
print(a.union(b))#union
print(a.intersection(b))#intersection
print(a.difference(b))#difference
print(a.symmetric_difference(b))#symmetric difference
print(a.issuperset(b))
print(a.issubset(b))
print(a.isdisjoint(b))

<class 'set'>
{1, 2, 3, 4}
{1, 2, 91, 36}
{'here', 'hii'}
{1, 2, 3, 4}
{1, 2, 3, 6, 9}
{1, 3, 6, 9}
{1, 2, 3, 4, 6, 9}
{1, 2, 6}
{3, 4}
{3, 4, 9}
False
False
False
