In [2]:
import numpy as np#import numpy


In [ ]:
a=np.arange(1,13).reshape(3,4)#range(1,13) using reshape(row,column)
print(a)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
a1=np.linspace(48,56,12).reshape(3,4)#using linspace(start,stop,no of halfs) while using we have to convert reshape while using creating
print(a1)

[[48.         48.72727273 49.45454545 50.18181818]
 [50.90909091 51.63636364 52.36363636 53.09090909]
 [53.81818182 54.54545455 55.27272727 56.        ]]


In [ ]:
a2=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a3=np.array([1,2,3,4,5,6,7,8,9])
a3.resize(2,2,2)
print(a3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#subtraction on each element
a=np.array([36,48,72])
b=np.array([3,6,9])
c=a-b
print(c)

[33 42 63]


In [ ]:
#Addition on each element
a=np.array([33,57,221])
b=np.array([2,5,9])
c=a+b
print(c)

[ 35  62 230]


In [ ]:
#multiplication on each element
a=np.array([2,6,9,72,19,3]).reshape(2,3)
b=np.array([3,4,7,2,1,4]).reshape(2,3)
c=a*b
print(a)
print("________________")
print(b)
print("_________________")
print(c)

[[ 2  6  9]
 [72 19  3]]
________________
[[3 4 7]
 [2 1 4]]
_________________
[[  6  24  63]
 [144  19  12]]


In [ ]:
#matrix multiplication
a=np.array([9,7,4,6]).reshape(2,2)
b=np.array([2,5,3,6]).reshape(2,2)

print(a)
print("________________")
print(b)
print("_________________")
d=a@b
print(d)

[[9 7]
 [4 6]]
________________
[[2 5]
 [3 6]]
_________________
[[39 87]
 [26 56]]


In [ ]:
a=np.array([2,6,9,72]).reshape(2,2)
b=np.array([3,4,7,2]).reshape(2,2)

print(a)
print("________________")
print(b)
print("_________________")
c=a.dot(b)
print(c)

[[ 2  6]
 [ 9 72]]
________________
[[3 4]
 [7 2]]
_________________
[[ 48  20]
 [531 180]]


In [ ]:
a=np.array([2.36,2.54,154,9.76,6,454])
print("max=",a.max())
print("min=",a.min())

max= 454.0
min= 2.36


In [ ]:
a=np.array([1,4,3,6,7,9,2,43,23,142,122,124,999])
print("max=",a.max())
print("min=",a.min())

max= 999
min= 1


In [3]:
a=np.array([1,2,3,5]).reshape(2,2)
print(a)
print(a.min(axis=0))#axis =0 is columns wise
print(a.min(axis=1))#aixs=1 is row wise

[[1 2]
 [3 5]]
[1 2]
[1 3]


In [ ]:
a=np.array([1,2,3,5]).reshape(2,2)
print(a)
print(a.max(axis=0))#axis =0 is columns wise
print(a.max(axis=1))#aixs=1 is row wise

[[1 2]
 [3 5]]
[3 5]
[2 5]


In [ ]:
#joining arrays
a=np.array([2,6,9,72,19,3]).reshape(2,3)
b=np.array([3,4,7,2,1,4]).reshape(2,3)
print(a)
print("_____________")
print(b)
print("________________")
print("After vertically stacking arrays!")
print(np.vstack((a,b)))

[[ 2  6  9]
 [72 19  3]]
_____________
[[3 4 7]
 [2 1 4]]
________________
After vertically stacking arrays!
[[ 2  6  9]
 [72 19  3]
 [ 3  4  7]
 [ 2  1  4]]


In [ ]:
a=np.array([2,6,9,72,19,3]).reshape(2,3)
b=np.array([3,4,7,2,1,4]).reshape(2,3)
print(a)
print("_____________")
print(b)
print("________________")
print("After horizontally stacking arrays!")
print(np.hstack((a,b)))

[[ 2  6  9]
 [72 19  3]]
_____________
[[3 4 7]
 [2 1 4]]
________________
After horizontally stacking arrays!
[[ 2  6  9  3  4  7]
 [72 19  3  2  1  4]]


In [ ]:
a=np.array([2,6,9,72,19,3]).reshape(2,3)
b=np.array([3,4,7,2,1,4]).reshape(2,3)
print(a)
print("_____________")
print(b)
print("________________")
print("After stacking arrays!")
print(np.stack((a,b),axis=1))

[[ 2  6  9]
 [72 19  3]]
_____________
[[3 4 7]
 [2 1 4]]
________________
After stacking arrays!
[[[ 2  6  9]
  [ 3  4  7]]

 [[72 19  3]
  [ 2  1  4]]]


In [ ]:
a=np.array([2,6,9,72,19,3]).reshape(2,3)
b=np.array([3,4,7,2,1,4]).reshape(2,3)
print(a)
print("_____________")
print(b)
print("________________")
print("After vertically stacking arrays!")
print(np.stack((a,b),axis=0))

[[ 2  6  9]
 [72 19  3]]
_____________
[[3 4 7]
 [2 1 4]]
________________
After vertically stacking arrays!
[[[ 2  6  9]
  [72 19  3]]

 [[ 3  4  7]
  [ 2  1  4]]]


In [ ]:
a=np.arange(30).reshape(2,3,5)#original -->(2,3,5)  in dstack-->(3,5,2)
print(a)
print("after dstack")
print(np.dstack(a))#no.of rows --> no of groups
#no.of col in every group-->no.of rows in every gruop
#[0 0],[1 1],....

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
after dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
#!splitting arrays !]
a=np.arange(18).reshape(6,3)
print(a)
print("After spliting")
np.vsplit(a,3)#splits into rows

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After spliting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [ ]:
a=np.arange(18).reshape(6,3)
print(a)
print("After spliting")
np.vsplit(a,(2,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After spliting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])]

In [ ]:
a=np.arange(18).reshape(6,3)
a.resize(3,6)

print(a)
print("After spliting")
np.hsplit(a,(2,4))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
After spliting


[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

In [ ]:
a=np.arange(18).reshape(6,3)
print(a)
print(a.argmax())

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
17


In [ ]:
a=np.array([4,2,5,7856,232,54]).reshape(2,3)
print(a)
print(a.argmax())
print(a.argmax(axis=0))#[[0000][1111][2222]]
print(a.argmax(axis=1))#[[0123][0123][0123]]
print(a.argmin())

[[   4    2    5]
 [7856  232   54]]
3
[1 1 1]
[2 0]
1


Statistics

In [ ]:
#mean,median,variance,standard dev
a=np.array([12,34,25,66,66,71,81])
print("Mean",np.mean(a))
print("Median ",np.median(a))
print("variance ",np.var(a))
print("Standard Dev ",np.std(a))

Mean 50.714285714285715
Median  66.0
variance  605.0612244897959
Standard Dev  24.59799228574958


Trignometry

In [ ]:
a=np.pi
print(a)

3.141592653589793


In [ ]:
np.rad2deg(a)

180.0

In [ ]:
a=np.array([np.pi/4,np.pi/3,np.pi/2,np.pi/1])
print(a)

[0.78539816 1.04719755 1.57079633 3.14159265]


In [ ]:
np.rad2deg(a)

array([ 45.,  60.,  90., 180.])

In [ ]:
c=np.array([0,30,45,60,90,120,180])
d=np.deg2rad(c)
print(d)

[0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265]


In [ ]:
np.sin(c)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666,
        0.58061118, -0.80115264])

In [ ]:
np.cos(c)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362,
        0.81418097, -0.59846007])

In [ ]:
np.tan(c)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041,
        0.71312301,  1.33869021])

In [ ]:
np.arcsin(1) #sin inverse

1.5707963267948966

In [ ]:
np.arccos(1)

0.0

In [ ]:
np.arctan(1)

0.7853981633974483

In [ ]:
a=3
b=4
print(np.hypot(a,b))#hypotnuse

5.0


searching an array

In [ ]:
a=np.array([90,3,45,21,34,90,21])
print(np.where(a==90))

(array([0, 5]),)


In [ ]:
a=np.array([90,3,45,21,34,90,21])
print(np.where(a%2==0))

(array([0, 4, 5]),)


In [ ]:
print(np.where(a<50))

(array([1, 2, 3, 4, 6]),)


In [ ]:
#search sorted
'''create an array of elements 1d'''
a=np.array([4,5,6,12,18])
print(np.searchsorted(a,12))#outputs the index of a sorted element!

3


Linear algebra and Universal function

In [ ]:
a=np.array([6,24,60,12,18])
b=np.array([6,4,10,5,4])

print(np.add(a,b)) #addition
print(np.subtract(a,b))#subtraction

[12 28 70 17 22]
[ 0 20 50  7 14]


In [ ]:
np.divide(a,b)#division

array([1. , 6. , 6. , 2.4, 4.5])

In [ ]:
print(np.mod(a,b))

[0 0 0 2 2]


In [ ]:
print(np.divmod(a,b))

(array([1, 6, 6, 2, 4]), array([0, 0, 0, 2, 2]))


In [ ]:
a=np.array([21,34,67,21,45,21])
print(np.sort(a))

[21 21 21 34 45 67]


In [ ]:
a=np.array([21,34,67,21,45,99])#21,34,67,21,45,21 -->34-21=13
print(np.diff(a))

[ 13  33 -46  24  54]


set function

In [ ]:
a=np.array([6,24,60,12,18])
b=np.array([6,4,10,5,4])
print(np.union1d(a,b))

[ 4  5  6 10 12 18 24 60]


In [ ]:
print(np.setdiff1d(a,b)) #difference a-b

[12 18 24 60]


In [ ]:
print(np.intersect1d(a,b))

[6]


Round function

In [ ]:
b=np.trunc([-3.166,3.6667])
print(b)

[-3.  3.]


In [ ]:
b=np.fix([-3.666,3.6667])
print(b)

[-3.  3.]


In [ ]:
b=np.around(-3.1666,3)
print(b)

-3.167


In [ ]:
b=np.floor([-3.1666,3.6667])
print(b)

[-4.  3.]


In [ ]:
b=np.ceil([-3.1666,3.6667])
print(b)

[-3.  4.]


More functions !

In [ ]:
#cummulative sum
a=np.array([3,4,16,19,10])
print(np.cumsum(a))

[ 3  7 23 42 52]


In [ ]:
#cummulative product
a=np.array([3,4,16,19,10])
print(np.cumprod(a))

[    3    12   192  3648 36480]


In [ ]:
print("LCM = ",np.lcm(36,27))
print("GCD = ",np.gcd(57,6))

LCM =  108
GCD =  3


In [ ]:
print(np.lcm.reduce([54,65,34]))#lcm for multiple number using reduce function
print(np.gcd.reduce([34,54,63]))#gcd for multiple number using reduce function

59670
1


In [ ]:
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a))#linear algebra

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
from numpy import random as rd


In [ ]:
a=rd.rand()#n #default limit(0 to 0.99)
print(a)
a1=rd.rand(10)#n #default limit(0,0.99)
print(a1)
a2=rd.randint(4) #0,1,2,3
print(a2)
a3=rd.randint(50,size=6) #limit
print(a3)
a4=rd.randint(50,size=(2,3)) #limit
print(a4)

0.9978020155178657
[0.69402525 0.85552223 0.84184921 0.56685709 0.39262835 0.65880668
 0.4889729  0.06156921 0.72673828 0.86833254]
1
[24 26 26 31 42  9]
[[33 47 41]
 [ 7 12 22]]


joins !

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.inner(a,b))#1*4+2*5+3*6
print(np.outer(a,b))#[[4*1 5*1 6*1][4*2 5*2 6*2][4*3 5*3 6*3]]
print(np.cross(a,b))# -3==>2*6-3*5

32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
[-3  6 -3]
